### ISSUE TITLE
测试不过  

### ISSUE THREAD

**Issue by guijunchen** [xushirain/fabric-gm#2]
configtxlator cryptogen idemixgen 编译出来版本都是1.4.2

**Comment by xushirain** [comment]
我是基于v1.4.6改编的 不会出现1.4.2的
![image](https://user-images.githubusercontent.com/17526065/82729592-63b23780-9d2b-11ea-8a0b-db9b1cefdb24.png)

**Comment by xushirain** [comment]
![image](https://user-images.githubusercontent.com/17526065/82729603-6dd43600-9d2b-11ea-8945-e9b082b2e52d.png)

**Comment by xushirain** [comment]
长时间未回复 关闭此问题
